### ISSUE TITLE
Initialize OpenAI wrapper

### ISSUE THREAD

**Issue by kamka427** [know-lab/AssistantGPT#1]
Initialises the backend of the project. Provide a starter FastAPI based API and a wrapper for OpenAI's ChatCompletion API.

**Comment by krrishdholakia** [comment]
Hi @kamka427 - curious why you're creating a server for calling the openai endpoint? 

context - working on a proxy to translate openai calls to other models (Anthropic, Replicate, Azure, etc.) wondering if I can help 

https://docs.litellm.ai/docs/proxy_server

**Comment by kamka427** [comment]
Hi @krrishdholakia,

Thank you for checking out our project! We are working on a lab project at Eötvös Loránd University. The goal is to have a chat application, which can help inexperienced users to use computers efficiently writing commands to a chat instead of the terminal and provide workflow running capabilities to experienced users using the ChatGPT API.
Thank you for linking your project. I think it is a really good idea, as other models are getting popularity. I will check out your documentation. Sadly we can't accept contributions yet, as this project will be graded at the end of the semester, After that, if the project will be competitive, we will gladly accept any contributions.

Best Regards,
Kálmán
